DATALOADER:
  ASPECT_RATIO_GROUPING: false
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 0
DATASET:
  MIN_GT_FRAME: 4
  NAME: VidSTG
  NUM_CLIP_FRAMES: 32
DATA_DIR: ../dataset/vidstg
DATA_TRUNK: null
FROM_SCRATCH: true
GLOVE_DIR: ''
INPUT:
  AUG_SCALE: true
  AUG_TRANSLATE: false
  FLIP_PROB_TRAIN: 0.5
  IMAGE_MAX_SIZE: 224
  IMAGE_MIN_SIZE: 224
  MAX_QUERY_LEN: 26
  MAX_VIDEO_LEN: 200
  PIXEL_MEAN:
  - 0.485
  - 0.456
  - 0.406
  PIXEL_STD:
  - 0.229
  - 0.224
  - 0.225
  RESOLUTION: 224
  SAMPLE_FPS: 3.2
  TEMP_CROP_PROB: 0.5
  TRAIN_SAMPLE_NUM: 11
  VIDEO_SAMPLE_NUM: 50.0
MODEL:
  ATTENTION_PROBS_DROPOUT_PROB: 0.1
  BI_ATTENTION_TYPE: 1
  BI_HIDDEN_SIZE: 256
  BI_INTERMEDIATE_SIZE: 256
  BI_NUM_ATTENTION_HEADS: 8
  DEVICE: cuda
  DOWN_RATIO: 4
  EMA: true
  EMA_DECAY: 0.9998
  HIDDEN_ACT: gelu
  HIDDEN_DROPOUT_PROB: 0.1
  HIDDEN_SIZE: 256
  INITIALIZER_RANGE: 0.02
  INTERMEDIATE_SIZE: 3072
  LSTM:
    BIDIRECTIONAL: true
    DROPOUT: 0
    HIDDEN_SIZE: 512
    NAME: lstm
  LSTM_NUM_LAYERS: 2
  MAX_POSITION_EMBEDDINGS: 512
  NUM_ATTENTION_HEADS: 12
  NUM_HIDDEN_LAYERS: 12
  POOLING_METHOD: mul
  QUERY_NUM: 1
  STCAT:
    CONV_LAYERS: 4
    DEC_LAYERS: 6
    DROPOUT: 0.1
    ENC_LAYERS: 6
    FFN_DIM: 2048
    FROM_SCRATCH: true
    HEADS: 8
    HIDDEN: 256
    KERNAL_SIZE: 9
    MAX_MAP_SIZE: 128
    POOLING_COUNTS:
    - 15
    - 8
    - 8
    - 8
    QUERY_DIM: 4
    TEMP_HEAD: attn
    TEMP_PRED_LAYERS: 6
    USE_ACTION: true
    USE_LEARN_TIME_EMBED: false
    VISION_HIDDEN: 256
  TEXT_MODEL:
    FREEZE: false
    NAME: roberta-base
  TYPE_VOCAB_SIZE: 2
  T_BIATTENTION_ID:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  USE_DSDECOMPOSE: false
  USE_LSTM: false
  VISION_BACKBONE:
    DILATION: false
    FREEZE: false
    NAME: resnet101
    POS_ENC: sine
  VISUALIZATION: false
  VOCAB_SIZE: 30522
  V_ATTENTION_PROBS_DROPOUT_PROB: 0.1
  V_BIATTENTION_ID:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  V_FEATURE_SIZE: 2048
  V_HIDDEN_ACT: gelu
  V_HIDDEN_DROPOUT_PROB: 0.1
  V_HIDDEN_SIZE: 256
  V_INITIALIZER_RANGE: 0.02
  V_INTERMEDIATE_SIZE: 256
  V_NUM_ATTENTION_HEADS: 8
  V_NUM_HIDDEN_LAYERS: 6
  V_TARGET_SIZE: 1601
  WEIGHT: ''
OUTPUT_DIR: ''
SOLVER:
  ACTIONESS_COEF: 2
  ATTN_COEF: 1
  BASE_LR: 2.0e-05
  BATCH_SIZE: 1
  BBOX_COEF: 5
  CHECKPOINT_PERIOD: 5000
  EOS_COEF: 0.1
  GAMMA: 0.1
  GIOU_COEF: 2
  MAX_EPOCH: 30
  MAX_GRAD_NORM: 0.1
  MOMENTUM: 0.9
  OPTIMIZER: adamw
  POWER: 0.9
  PRE_VAL: false
  SCHEDULE:
    COOLDOWN: 1
    DROP_STEP:
    - 8
    - 12
    FACTOR: 0.5
    MAX_DECAY_STEP: 7
    PATIENCE: 2
    THRESHOLD: 0.0001
    TYPE: linear_with_warmup
  SHUFFLE: true
  SIGMA: 2.0
  STEPS:
  - 30000
  TEMP_COEF: 2
  TEMP_LR: 0.0001
  TEXT_LR: 2.0e-05
  TO_VAL: true
  USE_ATTN: true
  USE_AUX_LOSS: true
  VAL_PERIOD: 2500
  VIS_BACKBONE_LR: 1.0e-05
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  WARMUP_PROP: 0.01
  WEIGHT_DECAY: 0.0001
TENSORBOARD_DIR: ''
